const mongoose = require('mongoose');
const crypto = require('crypto');

/**
 * Certificate — Chapter 5 is explicit that certificates are NEVER
 * auto-generated by the system; an Admin always uploads a file prepared
 * outside NEXTGEN. This model just tracks that file, who it belongs to,
 * and download history. `certificateId` is the human-readable code shown
 * on the public verification page (QR points to a URL containing it).
 */
const certificateSchema = new mongoose.Schema(
  {
    workshop: { type: mongoose.Schema.Types.ObjectId, ref: 'Workshop', required: true },
    viewer: { type: mongoose.Schema.Types.ObjectId, ref: 'Viewer', required: true },
    certificateId: { type: String, unique: true, required: true },

    fileUrl: { type: String, trim: true, required: true },
    fileType: { type: String, enum: ['pdf', 'png', 'jpeg'], required: true },

    uploadedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'Admin', required: true },
    uploadedAt: { type: Date, default: Date.now },

    downloads: [{ at: { type: Date, default: Date.now } }],
  },
  { timestamps: true }
);

certificateSchema.index({ workshop: 1, viewer: 1 }, { unique: true });

certificateSchema.statics.generateCertificateId = function () {
  return 'NG-CERT-' + crypto.randomBytes(5).toString('hex').toUpperCase();
};

module.exports = mongoose.model('Certificate', certificateSchema);
